### PR TITLE
Add Linux AArch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Added linux aarch64 wheel build support.
Related to https://github.com/MSeifert04/iteration_utilities/issues/331, @MSeifert04  Could you please review this PR?

### CODE REVIEW

**Comment by MSeifert04** [comment]
Hi @odidev , thanks for the PR. I haven't been actively maintaining this project for a while. I did not notice that there is active interest in having it on aarch64 systems.

I'll check if the build succeeds (I guess I will need to add current python wheels anyway) and if it does I'll add them to the current release :)

**Comment by odidev** [comment]
> I'll check if the build succeeds (I guess I will need to add current python wheels anyway) and if it does I'll add them to the current release :)

@MSeifert04 Is there any update on this?

**Comment by MSeifert04** [comment]
I am a bit short on time at the moment. I tried it a few weeks back and seemed good (just a few cleanups necessary). I hope I can find some time at the weekend to get the build working again.

**Comment by MSeifert04** [comment]
I didn't find the time and I'm not sure if I can get to it soon.

**Comment by MSeifert04** [comment]
I'm not sure if this will be resolved by #339 but if it isn't I probably won't continue to add support for this because the Github actions are already taking a significant amount of time.

But thanks a lot for you contribution and the pull request 🎉

**Pull request closed without merging**
